name: Build Docker images

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
      - Dockerfile.*
      - bin/*
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-docker:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push - frxyt/cd-ssh:alpine
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.alpine
          push: true
          tags: |
            frxyt/cd-ssh:alpine
      - name: Build and push - frxyt/cd-ssh:debian
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.debian
          push: true
          tags: |
            frxyt/cd-ssh:debian
            frxyt/cd-ssh:latest